// src/components/scroller-elevator/index.tsx

import React from 'react';
import '@/assets/css/itv-theme.less'
import './itv-scroller-elevator.less'
import ScrollerContext from '../scroller/libs/provider';
import render from '../../libs/render';
export interface CellProps{
    name?: String,
    children: HTMLDivElement
    
}


 
class ScrollerElevator extends React.Component {
    static contextType = ScrollerContext;
    el = React.createRef();
    id = new Date().getTime() + parseInt(Math.random()*100000000);
   
    
    constructor(props:any) {
        super(props);
        this.state = {
            top: 0,
            height: 0,
            header: '',
            headerHeight: 0,
            maxY: 0,
            y: 0
        }
    }
    init =()=>{
        let dom = this.el.current;
        this.state.top = dom.offsetTop;
        this.state.height = dom.clientHeight;
        this.header = render(dom.children[0]);
        this.state.headerHeight = dom.children[0].clientHeight;
        this.state.maxY = this.state.height - this.state.headerHeight 
    }

    scroll = (res) =>{
       
        if(res.y > this.state.top ) {
            let y =res.y-this.state.top;
            if(y>this.state.maxY) {
                y = this.state.maxY
            }
            this.state.y = y
            this.header(0,-this.state.y,1)
        }else{
            this.state.y = 0
            this.header(0,-this.state.y,1)
        }
    }
    componentDidMount(){
       this.context.events[this.id] = this;
       this.init();
    }


    render(){
        return (
            <div ref={this.el} className="itv-scroll-evevator">
                <div className="itv-scroll-evevator-header" >
                    {this.props.title}
                </div>
                <div className="itv-scroll-evevator-body">
                    {this.props.children}
                </div>
            </div>
        )
    }
}

export default ScrollerElevator

// src/components/scroller-elevator/index.vue
<template>
    <div class="itv-scroll-evevator">
        <div class="itv-scroll-evevator-header" ref="header">
            <slot name="header">
                {{title}}
            </slot>
        </div>
        <div class="itv-scroll-evevator-body">
            <slot></slot>
        </div>
    </div>
</template>

<script>
import render from '../../libs/render';
export default {
    name:'itv-scroller-elevator',
    props: {
        title: {
            type: String,
            default:""
        }
    },
    data() {
        return {
            top: 0,
            height: 0,
            header: '',
            headerHeight: 0,
            maxY: 0,
            y: 0
        }
    },
    mounted() {
       this.init();
       this.$parent.$on('scroll', (res)=>{
           if(res.y > this.top ) {
               let y =res.y-this.top;
               if(y>this.maxY) {
                   y = this.maxY
               }
               this.y = y
               this.header(0,-this.y,1)
           }else{
               this.y = 0
               this.header(0,-this.y,1)
           }
       })

       this.$parent.$on('content', (res)=>{
           this.init();
       })
        
    },
    methods: {
        init() {
            this.top = this.$el.offsetTop;
            this.height = this.$el.clientHeight;
            this.header = render(this.$el.children[0]);
            this.headerHeight = this.$el.children[0].clientHeight;
            this.maxY = this.height - this.headerHeight;
        }
    }

}
</script>
<style lang="less">
@import '../../assets/css/itv-theme.less';
@import 'itv-scroller-elevator.less';
</style>
